apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rzslmzl0y-go
  janus-idp.io/tekton: rzslmzl0y-go
  backstage.io/kubernetes-id: rzslmzl0y-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rzslmzl0y-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
